# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProductList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProductList


  pod 'Apollo', '~> 0.53.0'
  pod 'SwiftLint'

  target 'ProductListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProductListUITests' do
    # Pods for testing
  end

end
